# -*- coding: utf-8 -*-
"""zscore_normalize_dead_patient_data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dJ6sT37fAI6LQzTZ7gioMxpF8Rjt-Pqc
"""

from google.colab import files
uploaded = files.upload()

#Performed zscore normalization on valuenum for each corresponding itemid 
#(specifically on ICU patients who met inclusion/exclusion criteria and are dead)
# Formula = (value - mean)/(stdev)

import math
import numpy as np
import pandas as pd

data = pd.read_csv("chartevents - dead.csv")

item_ids = data['itemid'].unique()   #find unique itemids
len(item_ids)                        #find length of itemids
size = (len(item_ids),3)             #define dimension of new matrix
mean_sigma_matrix  = np.zeros(size)     #create matrix that will store corresponding min and max of valuenum for every itemid

for x in range(len(item_ids)):      
  mean_sigma_matrix[x,0] = item_ids[x]
  mean_sigma_matrix[x,1] = data['valuenum'].loc[(data['itemid'] == item_ids[x]) & (data['valuenum'] != 'NaN')].mean()
  mean_sigma_matrix[x,2] = data['valuenum'].loc[(data['itemid'] == item_ids[x]) & (data['valuenum'] != 'NaN')].std()

for y in range(len(data)):
    result = np.where(mean_sigma_matrix == data['itemid'].loc[y]);
    if np.isnan(mean_sigma_matrix[result[0][0]][1]):
      mean_sigma_matrix[result[0][0]][1] = 100001;
    elif np.isnan(mean_sigma_matrix[result[0][0]][2]):
      mean_sigma_matrix[result[0][0]][2] = 100001;
    elif mean_sigma_matrix[result[0][0]][1] == mean_sigma_matrix[result[0][0]][2]:
      mean_sigma_matrix[result[0][0]][1] = 100001;
      mean_sigma_matrix[result[0][0]][2] = 100001;
    elif (mean_sigma_matrix[result[0][0]][2] == 0): 
      mean_sigma_matrix[result[0][0]][2] = 100001;   
    elif (mean_sigma_matrix[result[0][0]][1] != 100001) & (mean_sigma_matrix[result[0][0]][2] != 100001):
      data['valuenum'].loc[y] = (data['valuenum'].loc[y] -  mean_sigma_matrix[result[0][0]][1])/(mean_sigma_matrix[result[0][0]][2]);

data.to_csv(r"chartevents_dead_minmax_normalized.csv", index = False)
